plugin-prefix: "&f[&x&7&F&C&F&B&2Custom Rules&f] "

no-permission: "&cУ вас нет прав на использование этой команды."
info: "&6Используйте: &f/rules reload &6- для перезагрузки конфигурации"
reload-success: "&aКонфигурация успешно перезагружена!"
reload-error: "&cОшибка при перезагрузке конфигурации"
wrong-command: "&cНеизвестная подкоманда. Используйте §f/rules reload"