name: CustomRulesPlugin
version: '1.0-SNAPSHOT'
main: org.marensovich.customRulesPlugin.CustomRulesPlugin
api-version: '1.21'
permissions:
  customrules.use:
    description: "Позволяет использовать команду /rules"
    default: true
  customrules.reload:
    description: "Позволяет перезагружать конфигурацию плагина"
    default: op